apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
data:
  default.conf: |
    server {
      listen 5000 default_server;
      listen [::]:5000 default_server;

      root /var/www/phpmyadmin;
      index index.php;
      server_name localhost;

      location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
          return 404;
        }

        # Mitigate https://httpoxy.org/ vulnerabilities
        fastcgi_param HTTP_PROXY "";

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;

        # include the fastcgi_param setting
        include fastcgi_params;

        # SCRIPT_FILENAME parameter is used for PHP FPM determining
        #  the script name. If it is not set in fastcgi_params file,
        # i.e. /etc/nginx/fastcgi_params or in the parent contexts,
        # please comment off following line:
        fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin
        name: phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: host-ip
        volumeMounts:
        - name: phpmyadmin-config
          subPath: default.conf
          mountPath: /etc/nginx/http.d/default.conf
          readOnly: true
      volumes:
        - name: phpmyadmin-config
          configMap:
            name: phpmyadmin-config
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - port: 5000