apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  default.conf: |
    server {
      listen 5050 default_server;
      listen [::]:5050 default_server;

      root /var/www/wordpress;
      index index.php;

      location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
          return 404;
        }

        # Mitigate https://httpoxy.org/ vulnerabilities
        fastcgi_param HTTP_PROXY "";

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;

        # include the fastcgi_param setting
        include fastcgi_params;

        # SCRIPT_FILENAME parameter is used for PHP FPM determining
        #  the script name. If it is not set in fastcgi_params file,
        # i.e. /etc/nginx/fastcgi_params or in the parent contexts,
        # please comment off following line:
        fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        envFrom:
        - secretRef:
            name: account
        volumeMounts:
        - name: wordpress-config
          subPath: default.conf
          mountPath: /etc/nginx/http.d/default.conf
          readOnly: true
      volumes:
        - name: wordpress-config
          configMap:
            name: wordpress-config
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - port: 5050
