apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps
        name: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 20020
        - containerPort: 20021
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: ftp-data
      port: 20
    - name: ftp-command
      port: 21
    - name: pasv-min
      port: 20020
    - name: pasv-max
      port: 20021